Project ~/repository/vim
Project ~/repository/react
Project ~/repository/react-demo
Project ~/repository/react-int
Project ~/repository/bin
Project ~/repository/dotFile/vimfiles/plugins/vim-project
Project ~/repository/svelte-lazy
Project ~/.config/nvim
Project ~/repository/dotFile/vimfiles/plugins/vim-matchtag
Project ~/repository/words-server
Project ~/repository/words-frontend
Project ~/repository/vim-colors-solarized
Project ~/repository/vim-plugin-test
Project ~/repository/blogs-graphql
Project ~/repository/spring-demo
Project ~/repository/react-demo-test
Project ~/repository/dotFile/vimfiles/plugins/fzf.vim
Project ~/repository/dotFile/vimfiles/plugins/vim-svelte-plugin
Project ~/repository/dotFile/vimfiles/plugins/vim-vue-plugin
Project ~/repository/flashcard-wechat
Project ~/repository/aspell
Project ~/repository/dotFile/vimfiles/plugins/vim-test
Project ~/repository/svelte-kit-demo
Project ~/repository/dotFile
Project ~/repository/homework-wechat
Project ~/repository/svelte-mode
Project ~/repository/dotFile/vimfiles/plugins/vim-imagine
Project ~/repository/maven-demo
Project ~/repository/dotFile/vimfiles/plugins/nvim-treesitter
Project ~/repository/dotFile/vimfiles/plugins/vim-run
Project ~/repository/MyTomato-app
Project ~/repository/MyTomato-app-new
Project ~/repository/pinyin
Project ~/repository/pinyin-data
